/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.principal;

import br.com.biblioteca.view.aluno.BuscarAluno;
import br.com.biblioteca.view.aluno.CadastrarAluno;
import br.com.biblioteca.view.aluno.EditarALuno;
import br.com.biblioteca.view.aluno.RemoverAluno;
import br.com.bilbioteca.view.Funcionario.CadastroDeFuncionario;
import br.com.bilbioteca.view.Funcionario.RemoverFuncionario;

/**
 *
 * @author Usuario
 */
public class JFrameCrudAluno extends javax.swing.JFrame {
        
    private CadastrarAluno addAluno = new CadastrarAluno();
    private BuscarAluno buscarAluno = new BuscarAluno();
    private EditarALuno editarAluno = new EditarALuno();
    private RemoverAluno deletarAluno = new RemoverAluno();
    
            
    /**
     * Creates new form Crud
     */
    public JFrameCrudAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonADDAluno = new javax.swing.JButton();
        jButtonBuscarAluno = new javax.swing.JButton();
        jButtonEditarAluno = new javax.swing.JButton();
        jButtonDeletarAluno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonADDAluno.setForeground(new java.awt.Color(51, 102, 0));
        jButtonADDAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\add.png")); // NOI18N
        jButtonADDAluno.setText("ADICIONAR ALUNO");
        jButtonADDAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonADDAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jButtonBuscarAluno.setForeground(new java.awt.Color(0, 102, 51));
        jButtonBuscarAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscarAluno.setText("BUSCAR ALUNO");
        jButtonBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 30));

        jButtonEditarAluno.setForeground(new java.awt.Color(0, 102, 0));
        jButtonEditarAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\pencil_edit_write_pen_drawing-20.png")); // NOI18N
        jButtonEditarAluno.setText("EDITAR ALUNO");
        jButtonEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        jButtonDeletarAluno.setForeground(new java.awt.Color(0, 153, 0));
        jButtonDeletarAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\delet.png")); // NOI18N
        jButtonDeletarAluno.setText("DELETAR ALUNO");
        jButtonDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\Picture-26(bilbioteca).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDAlunoActionPerformed
       addAluno.setVisible(true);
    }//GEN-LAST:event_jButtonADDAlunoActionPerformed

    private void jButtonBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlunoActionPerformed
        buscarAluno.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarAlunoActionPerformed

    private void jButtonEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAlunoActionPerformed
        editarAluno.setVisible(true);
    }//GEN-LAST:event_jButtonEditarAlunoActionPerformed

    private void jButtonDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarAlunoActionPerformed
        deletarAluno.setVisible(true);
    }//GEN-LAST:event_jButtonDeletarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCrudAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDAluno;
    private javax.swing.JButton jButtonBuscarAluno;
    private javax.swing.JButton jButtonDeletarAluno;
    private javax.swing.JButton jButtonEditarAluno;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
