/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.principal;

import br.com.bilbioteca.view.livro.BuscarLivro;
import br.com.bilbioteca.view.livro.CadastrarLivro;
import br.com.bilbioteca.view.livro.EditarLivro;
import br.com.bilbioteca.view.livro.RemoverLivro;

/**
 *
 * @author Usuario
 */
public class JFrameCrudLivro extends javax.swing.JFrame {
    private CadastrarLivro addLivro = new CadastrarLivro();
    private BuscarLivro buscarLivro = new BuscarLivro();
    private EditarLivro editarLivro = new EditarLivro();
    private RemoverLivro deletarLivro = new RemoverLivro();
    /**
     * Creates new form JFrameCrudLivro
     */
    public JFrameCrudLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonADDLIVRO = new javax.swing.JButton();
        jButtonBuscarLIVRO = new javax.swing.JButton();
        jButtonEditarLIVRO = new javax.swing.JButton();
        jButtonDeletarLIVRO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonADDLIVRO.setForeground(new java.awt.Color(51, 102, 0));
        jButtonADDLIVRO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\add.png")); // NOI18N
        jButtonADDLIVRO.setText("ADICIONAR LIVRO");
        jButtonADDLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDLIVROActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonADDLIVRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jButtonBuscarLIVRO.setForeground(new java.awt.Color(0, 102, 51));
        jButtonBuscarLIVRO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscarLIVRO.setText("BUSCAR LIVRO");
        jButtonBuscarLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarLIVROActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarLIVRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 30));

        jButtonEditarLIVRO.setForeground(new java.awt.Color(0, 102, 0));
        jButtonEditarLIVRO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\pencil_edit_write_pen_drawing-20.png")); // NOI18N
        jButtonEditarLIVRO.setText("EDITAR LIVRO");
        jButtonEditarLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarLIVROActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarLIVRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        jButtonDeletarLIVRO.setForeground(new java.awt.Color(0, 153, 0));
        jButtonDeletarLIVRO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\delet.png")); // NOI18N
        jButtonDeletarLIVRO.setText("DELETAR LIVRO");
        jButtonDeletarLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarLIVROActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarLIVRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\Picture-26(bilbioteca).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDLIVROActionPerformed
        addLivro.setVisible(true);
    }//GEN-LAST:event_jButtonADDLIVROActionPerformed

    private void jButtonBuscarLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarLIVROActionPerformed
        buscarLivro.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarLIVROActionPerformed

    private void jButtonEditarLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarLIVROActionPerformed
        editarLivro.setVisible(true);
    }//GEN-LAST:event_jButtonEditarLIVROActionPerformed

    private void jButtonDeletarLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarLIVROActionPerformed
        deletarLivro.setVisible(true);
    }//GEN-LAST:event_jButtonDeletarLIVROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCrudLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCrudLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDLIVRO;
    private javax.swing.JButton jButtonBuscarLIVRO;
    private javax.swing.JButton jButtonDeletarLIVRO;
    private javax.swing.JButton jButtonEditarLIVRO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
