/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.livro;

import br.com.biblioteca.controle.LivroControle;
import br.com.biblioteca.emprestimos.Livro;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class BuscarLivro extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    private Livro livro = new Livro();

    private LivroControle livroControle = new LivroControle();

    /**
     * Creates new form BuscarLivro
     */
    public BuscarLivro() {
        initComponents();
    }
     public void preencherTabela() {
         
         modelo.setRowCount(0);
         
        try {
            List<Livro> listarLivro = livroControle.listarLivro();
            //System.out.println(listarAluno);

            for (Livro livro : listarLivro) {

                modelo.addRow(new Object[]{livro.getId(), livro.getTitulo(), livro.getAno(),
                    livro.getArea(), livro.getAutor(), livro.getGenero(), livro.getDescricao(),
                    livro.getIsbn()
                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTabelaBuscarLivro.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    public void preencherTabelaPorNome(String nome) {
     
        modelo.setRowCount(0);
        

        try {
            List<Livro> listarLivro = livroControle.BuscarLivroPorNome(nome); 

            for (Livro livro : listarLivro) {

                modelo.addRow(new Object[]{livro.getId(), livro.getTitulo(), livro.getAno(),
                    livro.getArea(), livro.getAutor(), livro.getGenero(), livro.getDescricao(), 
                    livro.getIsbn()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTabelaBuscarLivro.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaBuscarLivro = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldtitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar Livros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTabelaBuscarLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabelaBuscarLivro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, 250));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 120, 30));
        getContentPane().add(jTextFieldtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 220, 30));

        jLabel2.setText("TITULO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 80, 38));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String titulo = jTextFieldtitulo.getText();
       
        preencherTabelaPorNome(titulo);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        modelo = (DefaultTableModel) jTabelaBuscarLivro.getModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("TITULO");
        modelo.addColumn("ANO");
        modelo.addColumn("AREA");
     
        modelo.addColumn("AUTOR");
        modelo.addColumn("GENERO");
        modelo.addColumn("DESCRICAO");
        modelo.addColumn("ISBN");
       
        jTabelaBuscarLivro.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTabelaBuscarLivro.getColumnModel().getColumn(0).setMaxWidth(0);
        jTabelaBuscarLivro.getColumnModel().getColumn(0).setMinWidth(0);

        jTabelaBuscarLivro.getColumnModel().getColumn(1).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(3).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(5).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(6).setPreferredWidth(400);
        jTabelaBuscarLivro.getColumnModel().getColumn(7).setPreferredWidth(400);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaBuscarLivro;
    private javax.swing.JTextField jTextFieldtitulo;
    // End of variables declaration//GEN-END:variables
}
