/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.livro;

import br.com.biblioteca.controle.LivroControle;
import br.com.biblioteca.emprestimos.Livro;
import br.com.biblioteca.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class RemoverLivro extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    
    private List<Livro> listarLivro = new ArrayList();
    
    private LivroControle livroControle = new LivroControle();

    /**
     * Creates new form RemoverLivro
     */
    public RemoverLivro() {
        initComponents();
    }
    
    public void preencherTabela() {
        modelo.setRowCount(0);

        try {
            List<Livro> listarLivro = livroControle.listarLivro();

            for (Livro livro : listarLivro) {

                modelo.addRow(new Object[]{livro.getId(), livro.getTitulo(), livro.getAno(),
                    livro.getArea(), livro.getAutor(), livro.getGenero(), livro.getDescricao(),
                    livro.getIsbn()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableExcluirLivro.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcluirLivro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableExcluirLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableExcluirLivro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 620, 226));

        jLabel1.setText("Remover Livro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 93, 34));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTableExcluirLivro.getSelectedRow() == -1) {
            
JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE_ELEMENTO_TABELA,"Livro"));
        //JOptionPane.showMessageDialog(null, "Selecione um elemento da tabela!");
        } else {
            int linha = jTableExcluirLivro.getSelectedRow();
            
            int idLivro = (Integer) modelo.getValueAt(linha, 0);
                try {
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_PERGUNTA_REMOCAO_TABELA,"Livro?"));    
                //int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover esse Livro ?", "removido", JOptionPane.YES_NO_OPTION);     
                
                livroControle.RemoverLivro(idLivro);
                
                preencherTabela();
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_REMOVIDO_SUCESSO,"Livro"));

            } catch (Exception ex) {
                Logger.getLogger(RemoverLivro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        modelo = (DefaultTableModel) jTableExcluirLivro.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("TITULO");
        modelo.addColumn("ANO");
        modelo.addColumn("AREA");
        modelo.addColumn("AUTOR");
        modelo.addColumn("GENERO");
        modelo.addColumn("DESCRIÇÃO");
        modelo.addColumn("ISBN");

        jTableExcluirLivro.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableExcluirLivro.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExcluirLivro.getColumnModel().getColumn(0).setMinWidth(0);

        jTableExcluirLivro.getColumnModel().getColumn(1).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(3).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(5).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(6).setPreferredWidth(400);
        jTableExcluirLivro.getColumnModel().getColumn(7).setPreferredWidth(400);

        preencherTabela();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExcluirLivro;
    // End of variables declaration//GEN-END:variables
}
