/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.Funcionario;

import br.com.biblioteca.Modeloprincipal.Endereco;
import br.com.biblioteca.Modeloprincipal.Funcionario;
import br.com.biblioteca.controle.FuncionarioControle;
import br.com.biblioteca.facede.ImplFacade;
import static java.nio.file.Files.list;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class BuscarFuncionario extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    private Funcionario funcionario = new Funcionario();

    private FuncionarioControle funcionarioControle = new FuncionarioControle();

    private List<Funcionario> func = new ArrayList<Funcionario>();

    /**
     * Creates new form BuscarFuncionario
     */
    public BuscarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void preencherTabela() {

        try {
            List<Funcionario> listarFuncionario = funcionarioControle.listarFuncionario();
            // System.out.println(listarFuncionario);

            for (Funcionario func : listarFuncionario) {

                modelo.addRow(new Object[]{func.getId(), func.getNome(), func.getCpf(),
                    func.getRg(), func.getCargo(), func.getDataAdmicao()
                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableBuscarFuncionario.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void preencherTabelaPorNome(String nome) {
        //tava faltando essa linha ai
        modelo.setRowCount(0);
        Endereco endereco = new Endereco();

        try {
            List<Funcionario> listarfuncionario = funcionarioControle.BuscarFuncionarioPorNome(nome);

            for (Funcionario funcionario : listarfuncionario) {

                modelo.addRow(new Object[]{funcionario.getId(), funcionario.getNome(), funcionario.getCpf(),
                    funcionario.getRg(), funcionario.getCargo(), funcionario.getDataAdmicao(),
//                    endereco.getId(), endereco.getRua(), endereco.getNumero(),endereco.getBairro(),endereco.getComplemento(),
  //                  endereco.getCidade(),endereco.getCidade(),endereco.getCep()
                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableBuscarFuncionario.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuscarFuncionario = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar Funcionario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 100, 32));

        jTableBuscarFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableBuscarFuncionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1040, 290));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 120, 30));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 220, 30));

        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        modelo = (DefaultTableModel) jTableBuscarFuncionario.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("CARGO");
        modelo.addColumn("DATA DE ADMIÇÃO");
        
//        modelo.addColumn("IDENDERECO");
//        modelo.addColumn("RUA");
//        modelo.addColumn("NUMERO");
//        modelo.addColumn("BAIRRO");
//        modelo.addColumn("COMPLEMENTO");
//        modelo.addColumn("CIDADE");
//        modelo.addColumn("CEP");
//        
//        modelo.addColumn("IDTELEFONE");
//        modelo.addColumn("CELULAR_01");
//        modelo.addColumn("CELULAR_02");
//        modelo.addColumn("TELEFONE-FIXO");

        jTableBuscarFuncionario.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableBuscarFuncionario.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableBuscarFuncionario.getColumnModel().getColumn(0).setMinWidth(0);

        jTableBuscarFuncionario.getColumnModel().getColumn(1).setPreferredWidth(700);
        jTableBuscarFuncionario.getColumnModel().getColumn(2).setPreferredWidth(600);
        jTableBuscarFuncionario.getColumnModel().getColumn(3).setPreferredWidth(500);
        jTableBuscarFuncionario.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTableBuscarFuncionario.getColumnModel().getColumn(5).setPreferredWidth(700);
        
//        jTableBuscarFuncionario.getColumnModel().getColumn(6).setPreferredWidth(0);
//        jTableBuscarFuncionario.getColumnModel().getColumn(6).setMaxWidth(0);
//        jTableBuscarFuncionario.getColumnModel().getColumn(6).setMinWidth(0);
//        
//        jTableBuscarFuncionario.getColumnModel().getColumn(7).setPreferredWidth(400);
//        jTableBuscarFuncionario.getColumnModel().getColumn(8).setPreferredWidth(400);
//        jTableBuscarFuncionario.getColumnModel().getColumn(9).setPreferredWidth(400);
//        jTableBuscarFuncionario.getColumnModel().getColumn(10).setPreferredWidth(400); 
//        jTableBuscarFuncionario.getColumnModel().getColumn(11).setPreferredWidth(400);
//        jTableBuscarFuncionario.getColumnModel().getColumn(12).setPreferredWidth(400);
//        
//        jTableBuscarFuncionario.getColumnModel().getColumn(13).setPreferredWidth(0);
//        jTableBuscarFuncionario.getColumnModel().getColumn(13).setMaxWidth(0);
//        jTableBuscarFuncionario.getColumnModel().getColumn(13).setMinWidth(0);
//
//
//        jTableBuscarFuncionario.getColumnModel().getColumn(14).setPreferredWidth(400); 
//        jTableBuscarFuncionario.getColumnModel().getColumn(15).setPreferredWidth(400);
//        jTableBuscarFuncionario.getColumnModel().getColumn(16).setPreferredWidth(400);
//        //preencherTabela();4

    }//GEN-LAST:event_formWindowOpened

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String nome = jTextFieldNome.getText();
        preencherTabelaPorNome(nome);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuscarFuncionario;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
