/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.Funcionario;

import br.com.biblioteca.view.aluno.CadastrarAluno;
import br.com.biblioteca.Modeloprincipal.Endereco;
import br.com.biblioteca.facede.IFacade;
import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.Modeloprincipal.Funcionario;
import br.com.biblioteca.Modeloprincipal.Telefone;
import br.com.biblioteca.controle.FuncionarioControle;
import br.com.biblioteca.util.DateUtil;
import br.com.biblioteca.util.MensagensUtil;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CadastroDeFuncionario extends javax.swing.JFrame {

    private Funcionario funcionario = new Funcionario();

    private FuncionarioControle funcionarioControle = new FuncionarioControle();

    /**
     * Creates new form CadastroDeFuncionario
     */
    public CadastroDeFuncionario() {
        initComponents();
    }

    CadastroDeFuncionario(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLCadatroDeFuncionario = new javax.swing.JLabel();
        JL = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JL2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        JL4 = new javax.swing.JLabel();
        JTFCargo = new javax.swing.JTextField();
        JL6 = new javax.swing.JLabel();
        JFormateDataAdmição = new javax.swing.JFormattedTextField();
        jFormateCpf = new javax.swing.JFormattedTextField();
        jFormateRG = new javax.swing.JFormattedTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTexNumero = new javax.swing.JTextField();
        jTextRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTexcomplemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextCep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormatteCelular01 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedCelular02 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTelefoneFixo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLCadatroDeFuncionario.setText("Cadastro de Funcionario");
        getContentPane().add(JLCadatroDeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        JL.setText("Nome");
        getContentPane().add(JL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 305, -1));

        JL2.setText("CPF");
        getContentPane().add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, -1));

        j3.setText("RG");
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 99, -1, -1));

        JL4.setText("CARGO");
        getContentPane().add(JL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));
        getContentPane().add(JTFCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 112, -1));

        JL6.setText("DATA DE ADMIÇÃO");
        getContentPane().add(JL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        try {
            JFormateDataAdmição.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFormateDataAdmição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFormateDataAdmiçãoActionPerformed(evt);
            }
        });
        getContentPane().add(JFormateDataAdmição, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, 76, -1));

        try {
            jFormateCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormateCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 112, -1));

        try {
            jFormateRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormateRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 119, 80, -1));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\delet.png")); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, 30));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\accept.png")); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 100, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\casdatro.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, 180));

        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("ENDEREÇO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 20));

        jLabel3.setText("RUA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel4.setText("Nº");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));
        getContentPane().add(jTexNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 40, -1));
        getContentPane().add(jTextRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        jLabel5.setText("BAIRRO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(jTextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, -1));

        jLabel6.setText("COMPLEMENTO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));
        getContentPane().add(jTexcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, -1));

        jLabel7.setText("CIDADE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, 20));
        getContentPane().add(jTextCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 120, -1));

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));
        getContentPane().add(jTextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 80, -1));

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("CONTATOS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel10.setText("CELUAR01");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        try {
            jFormatteCelular01.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteCelular01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 80, -1));

        jLabel11.setText("CELULAR02");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        try {
            jFormattedCelular02.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedCelular02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 80, -1));

        jLabel12.setText("TELEFONE FIXO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        try {
            jFormattedTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTelefoneFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        // TODO add your handlin code here:
    }//GEN-LAST:event_JTFNomeActionPerformed

    private void JFormateDataAdmiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFormateDataAdmiçãoActionPerformed

    }//GEN-LAST:event_JFormateDataAdmiçãoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        String nome = JTFNome.getText();
        String cpf = jFormateCpf.getText();
        String rg = jFormateRG.getText();
        String cargo = JTFCargo.getText();

        String data = JFormateDataAdmição.getText();
        DateUtil datautil = new DateUtil();
        Date dtnasc = datautil.stringToDate(data);
        
        String rua = jTextRua.getText();
        String numero = jTexNumero.getText();
        String bairro = jTextBairro.getText();
        String complemento = jTexcomplemento.getText();
        String cidade = jTextCidade.getText();
        String cep = jTextCep.getText();

        funcionario.setNome(nome);
        funcionario.setCpf(cpf);
        funcionario.setRg(rg);
        funcionario.setCargo(cargo);

        funcionario.setDataAdmicao(dtnasc);
        
        String celular01 = jFormatteCelular01.getText();
        String celular02 = jFormattedCelular02.getText();
        String telefoneFixo = jFormattedTelefoneFixo.getText();
        
         Endereco endereco = new Endereco();

            endereco.setRua(rua);
            endereco.setNumero(numero);
            endereco.setBairro(bairro);
            endereco.setComplemento(complemento);
            endereco.setCidade(cidade);
            endereco.setCep(cep);
            
            funcionario.setEnderecoFuncionario(endereco);

        Telefone telefone = new Telefone();

        telefone.setCelular01(celular01);
        telefone.setCelular02(celular02);
        telefone.setTelefoneFixo(telefoneFixo);
        
        funcionario.setTelefoneFuncionario(telefone);

 try {
            funcionarioControle.SalvarFuncionario(funcionario);
            //JOptionPane.showMessageDialog(null,"Cliente SALVO com sucesso!");
            int resp = JOptionPane.showConfirmDialog(null, "Salvar cadastro do Funcionario?", "Cadastramento", JOptionPane.YES_NO_OPTION);
            if (resp == 0)
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SUCESSO_SALVAR_GENERICA,"Funcionario"));
            
           {
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_SALVAR, "Funcionario ", " Funcionario "));    
        //JOptionPane.showMessageDialog(null, "IMPOSSÍVEL inserir Funcionario!", "ERRO ao inserir o Funcionario!", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
      
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JFormateDataAdmição;
    private javax.swing.JLabel JL;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL6;
    private javax.swing.JLabel JLCadatroDeFuncionario;
    private javax.swing.JTextField JTFCargo;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JLabel j3;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormateCpf;
    private javax.swing.JFormattedTextField jFormateRG;
    private javax.swing.JFormattedTextField jFormatteCelular01;
    private javax.swing.JFormattedTextField jFormattedCelular02;
    private javax.swing.JFormattedTextField jFormattedTelefoneFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTexNumero;
    private javax.swing.JTextField jTexcomplemento;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCep;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextRua;
    // End of variables declaration//GEN-END:variables
}
