/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.Funcionario;

import br.com.biblioteca.Modeloprincipal.Funcionario;
import br.com.biblioteca.controle.FuncionarioControle;
import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.util.DateUtil;
import br.com.biblioteca.util.MensagensUtil;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class EditarFuncionario extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    int id;
    private Funcionario funcionario = new Funcionario();
    private FuncionarioControle funcionarioControle = new FuncionarioControle();

    /**
     * Creates new form EditarFuncionario
     */
    public EditarFuncionario() {
        initComponents();
    }
    
    public void preencherCampos() {
       
        int linha = jTableEditarFuncionario.getSelectedRow();

        if (linha < 0) {
             JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE_ELEMENTO_TABELA,"Funcionario"));
             //JOptionPane.showMessageDialog(null, "Escolha um Funcionario");
        } else {

            id = (Integer) jTableEditarFuncionario.getValueAt(linha, 0);
            
            String nome = (String) jTableEditarFuncionario.getValueAt(linha, 1);
            String cpf = (String) jTableEditarFuncionario.getValueAt(linha, 2);
            String Rg = (String) jTableEditarFuncionario.getValueAt(linha, 3);
            String cargo = (String) jTableEditarFuncionario.getValueAt(linha, 4);
             Date data =  (Date) jTableEditarFuncionario.getValueAt(linha, 5);
            //verificar a converção da data
//
//             String data = jFormatteDataAdmição.getText();
                  DateUtil datautil = new DateUtil();
             String dtnasc = datautil.dateToString(data);
             
          
           // DateUtil datautil = new DateUtil();
           // Date dtnasc = datautil.stringToDate(data);

            
            jTextFieldNome.setText(nome);
            jFormatteCpf.setText(cpf);
            jFormatteRg.setText(Rg);
            jTextFieldCargo.setText(cargo);
            jFormatteDataAdmição.setText(dtnasc);
            
        }

    }

    public void preencherTabela() {
        
        modelo.setRowCount(0);
         
        try {
            List<Funcionario> listarFuncionario = new ArrayList<Funcionario>();
            
            listarFuncionario = funcionarioControle.listarFuncionario();
            

            for (Funcionario funcinario : listarFuncionario) {
                
                modelo.addRow(new Object[]{funcinario.getId(), funcinario.getNome(), funcinario.getCpf(),
                    funcinario.getRg(), funcinario.getCargo(), funcinario.getDataAdmicao()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableEditarFuncionario.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Serve para inserir as informações do funcionario da Tabela pra os TextFields
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEditarFuncionario = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jFormatteCpf = new javax.swing.JFormattedTextField();
        jFormatteRg = new javax.swing.JFormattedTextField();
        DATADEADMICAO = new javax.swing.JLabel();
        jFormatteDataAdmição = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Editar Funcionario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTableEditarFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEditarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEditarFuncionarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableEditarFuncionarioMousePressed(evt);
            }
        });
        jTableEditarFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableEditarFuncionarioKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEditarFuncionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 560, 230));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, 40));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, 20));

        jLabel3.setText("Cpf:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jLabel4.setText("Rg:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel5.setText("Cargo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        jTextFieldCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 219, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\accept.png")); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        try {
            jFormatteCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormatteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatteCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFormatteCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 102, -1));

        try {
            jFormatteRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 78, -1));

        DATADEADMICAO.setText("DATA DE ADMIÇÃO");
        getContentPane().add(DATADEADMICAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        try {
            jFormatteDataAdmição.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteDataAdmição, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 90, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 240, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        preencherTabela();

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableEditarFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableEditarFuncionarioKeyPressed
    
    }//GEN-LAST:event_jTableEditarFuncionarioKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Funcionario f = new Funcionario();
        
        //int linha =  jTableEditarFuncionario.getSelectedRow();
        f.setId(id);
        f.setNome(jTextFieldNome.getText());
        f.setCpf(jFormatteCpf.getText());
        f.setRg(jFormatteRg.getText());
        f.setCargo(jTextFieldCargo.getText());
        
        //f.setId((Integer) jTableEditarFuncionario.getValueAt(linha, 0));
        
        String data = jFormatteDataAdmição.getText();
        DateUtil datautil = new DateUtil();
         Date dtnasc = datautil.stringToDate(data);
        f.setDataAdmicao(dtnasc);
        try {
            funcionarioControle.EditarFuncionario(f);
        } catch (Exception ex) {
            Logger.getLogger(EditarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editado esse Funcionario ?", "editar", JOptionPane.YES_NO_OPTION);
            if (resp == 0) 
        JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SUCESSO_EDITAR_GENERICA,"Funcionario"));
        
        jTextFieldNome.setText("");
        jFormatteCpf.setText("");
        jFormatteRg.setText("");
        jTextFieldCargo.setText("");
        jFormatteDataAdmição.setText("");
        preencherTabela();
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormatteCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormatteCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormatteCpfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        modelo = (DefaultTableModel) jTableEditarFuncionario.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("CARGO");
        modelo.addColumn("DATA DE ADMIÇÃO");

        jTableEditarFuncionario.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableEditarFuncionario.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableEditarFuncionario.getColumnModel().getColumn(0).setMinWidth(0);

        jTableEditarFuncionario.getColumnModel().getColumn(1).setPreferredWidth(900);
        jTableEditarFuncionario.getColumnModel().getColumn(2).setPreferredWidth(600);

        jTableEditarFuncionario.getColumnModel().getColumn(3).setPreferredWidth(350);
        jTableEditarFuncionario.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTableEditarFuncionario.getColumnModel().getColumn(5).setPreferredWidth(500);

        preencherTabela();

    }//GEN-LAST:event_formWindowOpened

    private void jTabelaEditarAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                                
        preencherCampos();
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableEditarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEditarFuncionarioMouseClicked
        preencherCampos();
    }//GEN-LAST:event_jTableEditarFuncionarioMouseClicked

    private void jTableEditarFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEditarFuncionarioMousePressed
        
    }//GEN-LAST:event_jTableEditarFuncionarioMousePressed

    private void jTextFieldCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DATADEADMICAO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormatteCpf;
    private javax.swing.JFormattedTextField jFormatteDataAdmição;
    private javax.swing.JFormattedTextField jFormatteRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEditarFuncionario;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
