/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bilbioteca.view.Funcionario;

import br.com.biblioteca.Modeloprincipal.Funcionario;
import br.com.biblioteca.controle.FuncionarioControle;
import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.util.MensagensUtil;
import static java.nio.file.Files.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class RemoverFuncionario extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    private List<Funcionario> listaFuncionario = new ArrayList();
    
    private FuncionarioControle funcionarioControle = new FuncionarioControle();

    /**
     * Creates new form RemoverFuncionario
     */
    public RemoverFuncionario() {
        initComponents();
    }

    public void preencherTabela() {
        
        modelo.setRowCount(0);
        DefaultTableModel modelo = new DefaultTableModel();

        //tava faltando essa linha ai
        modelo = (DefaultTableModel) jTableExcluirFuncionario.getModel();

        try {
            List<Funcionario> lista = funcionarioControle.listarFuncionario();
            

            for (Funcionario funcinario : lista) {

                modelo.addRow(new Object[]{funcinario.getId(), funcinario.getNome(), funcinario.getCpf(),
                    funcinario.getRg(), funcinario.getCargo(),funcinario.getDataAdmicao()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableExcluirFuncionario.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcluirFuncionario = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Excluir Funcionario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTableExcluirFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableExcluirFuncionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, 700, 210));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 93, 29));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTableExcluirFuncionario.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE_ELEMENTO_TABELA,"Funcionario"));
           // JOptionPane.showMessageDialog(null, "Selecione um elemento da tabela!");
        } else {
            int linha = jTableExcluirFuncionario.getSelectedRow();
            
            int idAluno = (Integer) modelo.getValueAt(linha, 0);
            
            try {
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_PERGUNTA_REMOCAO_TABELA,"Funcionario?"));
                        
                        //JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover esse Funcionario ?", "removido", JOptionPane.YES_NO_OPTION);
            
               
                funcionarioControle.RemoverFuncionario(idAluno);
                preencherTabela();
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_REMOVIDO_SUCESSO,"Funcionario"));
                
            } catch (Exception ex) {
                Logger.getLogger(RemoverFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        modelo = (DefaultTableModel) jTableExcluirFuncionario.getModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("CARGO");
        modelo.addColumn("DATA DE ADMIÇÃO");
        
        jTableExcluirFuncionario.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableExcluirFuncionario.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExcluirFuncionario.getColumnModel().getColumn(0).setMinWidth(0);
        
        
        jTableExcluirFuncionario.getColumnModel().getColumn(1).setPreferredWidth(900);
        jTableExcluirFuncionario.getColumnModel().getColumn(2).setPreferredWidth(600);
        
        jTableExcluirFuncionario.getColumnModel().getColumn(3).setPreferredWidth(350);
        jTableExcluirFuncionario.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTableExcluirFuncionario.getColumnModel().getColumn(5).setPreferredWidth(500);
        
        preencherTabela();        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExcluirFuncionario;
    // End of variables declaration//GEN-END:variables
}
