/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view.aluno;

import br.com.biblioteca.Modeloprincipal.Aluno;
import br.com.biblioteca.Modeloprincipal.Endereco;
import br.com.biblioteca.controle.AlunoControle;
import br.com.biblioteca.facede.ImplFacade;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class BuscarAluno extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    private Aluno aluno = new Aluno();

    private AlunoControle alunoControle = new AlunoControle();
    /**
     * Creates new form BuscarAluno
     */
    public BuscarAluno() {
        initComponents();
    }

    public void preencherTabela() {
        //tava faltando essa linha ai
        modelo.setRowCount(0);
        Endereco endereco = new Endereco();

        try {
            List<Aluno> listarAluno = alunoControle.listarAlunos();
            //System.out.println(listarAluno);

            for (Aluno aluno : listarAluno) {

                modelo.addRow(new Object[]{aluno.getId(), aluno.getNome(), aluno.getCpf(),
                    aluno.getRg(), aluno.getPeriodo(), aluno.getMatricula(), aluno.getCurso(),
//                    endereco.getId(), endereco.getRua(), endereco.getNumero(),endereco.getBairro(),endereco.getComplemento(),
  //                  endereco.getCidade(),endereco.getCidade(),endereco.getCep()
                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTabelaBuscarAluno.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    public void preencherTabelaPorNome(String nome) {
        //tava faltando essa linha ai
        modelo.setRowCount(0);
        Endereco endereco = new Endereco();

        try {
            List<Aluno> listarAluno = alunoControle.BuscarAlunoPorNome(nome); 
            

            for (Aluno aluno : listarAluno) {
            

                modelo.addRow(new Object[]{aluno.getId(), aluno.getNome(), aluno.getCpf(),
                    aluno.getRg(), aluno.getPeriodo(), aluno.getMatricula(), aluno.getCurso(), 
                    
//                    endereco.getId(), endereco.getRua(), endereco.getNumero(),endereco.getBairro(),endereco.getComplemento(),
  //                  endereco.getCidade(),endereco.getCidade(),endereco.getCep()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTabelaBuscarAluno.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaBuscarAluno = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar Aluno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 80, 38));

        jTabelaBuscarAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabelaBuscarAluno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1070, 270));

        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 220, 30));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\search.png")); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        modelo = (DefaultTableModel) jTabelaBuscarAluno.getModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("PERIODO");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("CURSO");
        
//        modelo.addColumn("IDENDERECO");
//        modelo.addColumn("RUA");
//        modelo.addColumn("NUMERO");
//        modelo.addColumn("BAIRRO");
//        modelo.addColumn("COMPLEMENTO");
//        modelo.addColumn("CIDADE");
//        modelo.addColumn("CEP");
//        
//        modelo.addColumn("IDTELEFONE");
//        modelo.addColumn("CELULAR_01");
//        modelo.addColumn("CELULAR_02");
//        modelo.addColumn("TELEFONE-FIXO");
        

        jTabelaBuscarAluno.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTabelaBuscarAluno.getColumnModel().getColumn(0).setMaxWidth(0);
        jTabelaBuscarAluno.getColumnModel().getColumn(0).setMinWidth(0);

        jTabelaBuscarAluno.getColumnModel().getColumn(1).setPreferredWidth(700);
        jTabelaBuscarAluno.getColumnModel().getColumn(2).setPreferredWidth(600);
        jTabelaBuscarAluno.getColumnModel().getColumn(3).setPreferredWidth(500);
        jTabelaBuscarAluno.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTabelaBuscarAluno.getColumnModel().getColumn(5).setPreferredWidth(700);
        jTabelaBuscarAluno.getColumnModel().getColumn(6).setPreferredWidth(750);
        
//        jTabelaBuscarAluno.getColumnModel().getColumn(7).setPreferredWidth(0);
//        jTabelaBuscarAluno.getColumnModel().getColumn(7).setMaxWidth(0);
//        jTabelaBuscarAluno.getColumnModel().getColumn(7).setMinWidth(0);
//        
//        jTabelaBuscarAluno.getColumnModel().getColumn(8).setPreferredWidth(400);
//        jTabelaBuscarAluno.getColumnModel().getColumn(9).setPreferredWidth(400);
//        jTabelaBuscarAluno.getColumnModel().getColumn(10).setPreferredWidth(400);
//        jTabelaBuscarAluno.getColumnModel().getColumn(11).setPreferredWidth(400); 
//        jTabelaBuscarAluno.getColumnModel().getColumn(12).setPreferredWidth(400);
//        jTabelaBuscarAluno.getColumnModel().getColumn(13).setPreferredWidth(400);
//        
//        
//        jTabelaBuscarAluno.getColumnModel().getColumn(14).setPreferredWidth(0);
//        jTabelaBuscarAluno.getColumnModel().getColumn(14).setMaxWidth(0);
//        jTabelaBuscarAluno.getColumnModel().getColumn(14).setMinWidth(0);
//        
//        jTabelaBuscarAluno.getColumnModel().getColumn(15).setPreferredWidth(400); 
//        jTabelaBuscarAluno.getColumnModel().getColumn(16).setPreferredWidth(400); 
//        jTabelaBuscarAluno.getColumnModel().getColumn(17).setPreferredWidth(400); 
       
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
            String nome  = jTextFieldNome.getText();
            preencherTabelaPorNome(nome);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaBuscarAluno;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
