/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view.aluno;

import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.Modeloprincipal.Aluno;
import br.com.biblioteca.Modeloprincipal.Endereco;
import br.com.biblioteca.controle.AlunoControle;
import br.com.biblioteca.util.DateUtil;
import br.com.biblioteca.Modeloprincipal.Telefone;
import br.com.biblioteca.util.MensagensUtil;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class CadastrarAluno extends javax.swing.JFrame {

    private Aluno aluno = new Aluno();

    private AlunoControle alunoControle = new AlunoControle();

    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL1 = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JL4 = new javax.swing.JLabel();
        JTFPeriodo = new javax.swing.JTextField();
        JL5 = new javax.swing.JLabel();
        JTFMatricula = new javax.swing.JTextField();
        JL6 = new javax.swing.JLabel();
        JTFCurso = new javax.swing.JTextField();
        JButtonSalvar = new javax.swing.JButton();
        JButtonCancelar = new javax.swing.JButton();
        jFormateCpf = new javax.swing.JFormattedTextField();
        jFormateRG = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTexNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jTexcomplemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormatteCelular01 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedCelular02 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTelefoneFixo = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextCep = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL1.setText("Nome:");
        getContentPane().add(JL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 38, -1, -1));

        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 63, 317, -1));

        JL2.setText("CPF:");
        getContentPane().add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 92, -1, -1));

        jL3.setText("RG:");
        getContentPane().add(jL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 92, -1, -1));

        jLabel2.setText("Cadastro de Aluno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));

        JL4.setText("PERIODO:");
        getContentPane().add(JL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 92, -1, -1));
        getContentPane().add(JTFPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 112, 24, -1));

        JL5.setText("MATRICULA:");
        getContentPane().add(JL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 152, -1, 20));
        getContentPane().add(JTFMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 178, 170, -1));

        JL6.setText("CURSO:");
        getContentPane().add(JL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));
        getContentPane().add(JTFCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, -1));

        JButtonSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\accept.png")); // NOI18N
        JButtonSalvar.setText("Salvar");
        JButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 110, 30));

        JButtonCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\delet.png")); // NOI18N
        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        try {
            jFormateCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormateCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormateCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFormateCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 112, 170, -1));

        try {
            jFormateRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormateRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 112, 80, -1));

        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("ENDEREÇO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 20));

        jLabel3.setText("RUA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(jTexNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 40, -1));

        jLabel4.setText("Nº");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        getContentPane().add(jTextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, -1));

        jLabel5.setText("BAIRRO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(jTextRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        jLabel6.setText("COMPLEMENTO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));
        getContentPane().add(jTextCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 120, -1));
        getContentPane().add(jTexcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 120, -1));

        jLabel7.setText("CIDADE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\casdatro.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 130, 180));

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("CONTATOS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        try {
            jFormatteCelular01.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteCelular01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, -1));

        jLabel10.setText("CELUAR01");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel11.setText("CELULAR02");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        try {
            jFormattedCelular02.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedCelular02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, -1));

        jLabel12.setText("TELEFONE FIXO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        try {
            jFormattedTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTelefoneFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 80, -1));

        jLabel13.setText("CEP:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));
        getContentPane().add(jTextCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        /**
         * JLNome = new JTextField(); JLNome.setToolTipText("Informe seu nome
         * "); JLNome.setBounds(94, 44, 257, 20); CadastrarAluno.add(JLNome);*
         */

    }//GEN-LAST:event_JTFNomeActionPerformed

    private void jFormateCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormateCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormateCpfActionPerformed

    private void JButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalvarActionPerformed

        String nome = JTFNome.getText();
        String cpf = jFormateCpf.getText();
        String rg = jFormateRG.getText();
        String periodo = JTFPeriodo.getText();
        String matricula = JTFMatricula.getText();
        String curso = JTFCurso.getText();

        String rua = jTextRua.getText();
        String numero = jTexNumero.getText();
        String bairro = jTextBairro.getText();
        String complemento = jTexcomplemento.getText();
        String cidade = jTextCidade.getText();
        String cep = jTextCep.getText();

        aluno.setNome(nome);
        aluno.setCpf(cpf);
        aluno.setRg(rg);
        aluno.setPeriodo(periodo);
        aluno.setMatricula(matricula);
        aluno.setCurso(curso);

        String celular01 = jFormatteCelular01.getText();
        String celular02 = jFormattedCelular02.getText();
        String telefoneFixo = jFormattedTelefoneFixo.getText();

        Endereco endereco = new Endereco();

        endereco.setRua(rua);
        endereco.setNumero(numero);
        endereco.setBairro(bairro);
        endereco.setComplemento(complemento);
        endereco.setCidade(cidade);
        endereco.setCep(cep);

        aluno.setEnderecoAluno(endereco);

        Telefone telefone = new Telefone();

        telefone.setCelular01(celular01);
        telefone.setCelular02(celular02);
        telefone.setTelefoneFixo(telefoneFixo);

        aluno.setTelefoneAluno(telefone);

       //Aluno aluno = new Aluno();
        //aluno.setNome(nome);
        //aluno.setCpf(cpf);
        //aluno.setRg(rg);
        //aluno.setPeriodo(periodo);
        //aluno.setMatricula(matricula);
        //aluno.setCurso(curso);
        try {
            alunoControle.SalvarAluno(aluno);
            //JOptionPane.showMessageDialog(null,"Cliente SALVO com sucesso!");
            int resp = JOptionPane.showConfirmDialog(null, "Salvar cadastro do Aluno?", "Cadastramento", JOptionPane.YES_NO_OPTION);
            if (resp == 0)
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SUCESSO_SALVAR_GENERICA,"Aluno"));
           
            {
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "IMPOSSÍVEL inserir Aluno!", "ERRO ao inserir o Aluno!", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_SALVAR, "Aluno ", " Aluno "));

        }

        JTFNome.setText("");
        jFormateCpf.setText("");
        jFormateRG.setText("");
        JTFPeriodo.setText("");
        JTFMatricula.setText("");
        JTFCurso.setText("");

        jTextRua.setText("");
        jTexNumero.setText("");
        jTextBairro.setText("");
        jTexcomplemento.setText("");
        jTextCidade.setText("");
        jTextCep.setText("");

        jFormatteCelular01.setText("");
        jFormattedCelular02.setText("");
        jFormattedTelefoneFixo.setText("");

    }//GEN-LAST:event_JButtonSalvarActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonSalvar;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL5;
    private javax.swing.JLabel JL6;
    private javax.swing.JTextField JTFCurso;
    private javax.swing.JTextField JTFMatricula;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFPeriodo;
    private javax.swing.JFormattedTextField jFormateCpf;
    private javax.swing.JFormattedTextField jFormateRG;
    private javax.swing.JFormattedTextField jFormatteCelular01;
    private javax.swing.JFormattedTextField jFormattedCelular02;
    private javax.swing.JFormattedTextField jFormattedTelefoneFixo;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTexNumero;
    private javax.swing.JTextField jTexcomplemento;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCep;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextRua;
    // End of variables declaration//GEN-END:variables
}
