/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view.aluno;

import br.com.biblioteca.Modeloprincipal.Aluno;
import br.com.biblioteca.controle.AlunoControle;
import br.com.biblioteca.facede.IFacade;
import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.util.DaoFactory;
import br.com.biblioteca.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class EditarALuno extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    int id;

    private Aluno aluno = new Aluno();
    private AlunoControle alunoControle = new AlunoControle();

    //IFacade facade = DaoFactory.createImplFacade();
    //ImplFacade facade = new ImplFacade();
    /**
     * Creates new form EditarALuno
     */
    public EditarALuno() {
        initComponents();
    }

    public void preencherCampos() {

        int linha = jTabelaEditarAluno.getSelectedRow();

        if (linha < 0) {
           // JOptionPane.showMessageDialog(null, "Escolha um Aluno");
         JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE_ELEMENTO_TABELA,"Aluno"));
        } else {

            id = (Integer) jTabelaEditarAluno.getValueAt(linha, 0);

            //id = Integer.parseInt(id2);
            String nome = (String) jTabelaEditarAluno.getValueAt(linha, 1);
            String cpf = (String) jTabelaEditarAluno.getValueAt(linha, 2);
            String Rg = (String) jTabelaEditarAluno.getValueAt(linha, 3);
            String periodo = (String) jTabelaEditarAluno.getValueAt(linha, 4);
            String matricula = (String) jTabelaEditarAluno.getValueAt(linha, 5);
            String curso = (String) jTabelaEditarAluno.getValueAt(linha, 6);

            jTextFieldNome.setText(nome);
            jFormatteCpf.setText(cpf);
            jFormatteRg.setText(Rg);
            jTextFieldPeriodo.setText(periodo);
            jTextFieldMatricula.setText(matricula);
            jTextFieldCurso.setText(curso);

        }
    }

    public void preencherTabela() {

        modelo.setNumRows(0);

        try {
            //List<Aluno> listarAluno = alunoControle.listarAlunos();
            List<Aluno> listarAluno = new ArrayList<Aluno>();
            listarAluno = alunoControle.listarAlunos();
            //System.out.println(listarAluno);

            for (Aluno aluno : listarAluno) {

                modelo.addRow(new Object[]{aluno.getId(), aluno.getNome(), aluno.getCpf(),
                    aluno.getRg(), aluno.getPeriodo(), aluno.getMatricula(), aluno.getCurso()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTabelaEditarAluno.setModel(modelo);
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaEditarAluno = new javax.swing.JTable();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormatteRg = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPeriodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCurso = new javax.swing.JTextField();
        jFormatteCpf = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Editar Aluno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\accept.png")); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 110, 40));

        jTabelaEditarAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTabelaEditarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaEditarAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaEditarAluno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 290));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 244, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel3.setText("Cpf:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        try {
            jFormatteRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 102, -1));

        jLabel4.setText("Rg:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));
        getContentPane().add(jTextFieldPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 30, -1));

        jLabel7.setText("Periodo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jLabel5.setText("Matricula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));
        getContentPane().add(jTextFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 127, -1));

        jLabel6.setText("Curso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));
        getContentPane().add(jTextFieldCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 150, -1));

        try {
            jFormatteCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormatteCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 102, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Biblioteca\\src\\br\\com\\biblioteca\\incone\\delet.png")); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 110, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Aluno a = new Aluno();

        a.setId(id);

        a.setNome(jTextFieldNome.getText());
        a.setCpf(jFormatteCpf.getText());
        a.setRg(jFormatteRg.getText());
        a.setPeriodo(jTextFieldPeriodo.getText());
        a.setMatricula(jTextFieldMatricula.getText());
        a.setCurso(jTextFieldCurso.getText());

        try {
            alunoControle.EditarAluno(a);

            //facade.editarAluno(a);
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(EditarALuno.class.getName()).log(Level.SEVERE, null, ex);
        }

        int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editado esse Aluno?", "editar", JOptionPane.YES_NO_OPTION);
            if (resp == 0) 
        JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SUCESSO_EDITAR_GENERICA,"Aluno"));
        jTextFieldNome.setText("");
        jFormatteCpf.setText("");
        jFormatteRg.setText("");
        jTextFieldPeriodo.setText("");
        jTextFieldCurso.setText("");
        jTextFieldMatricula.setText("");

        preencherTabela();
        

    }//GEN-LAST:event_jButton1ActionPerformed


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        modelo = (DefaultTableModel) jTabelaEditarAluno.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("PERIODO");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("CURSO");

        jTabelaEditarAluno.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTabelaEditarAluno.getColumnModel().getColumn(0).setMaxWidth(0);
        jTabelaEditarAluno.getColumnModel().getColumn(0).setMinWidth(0);

        jTabelaEditarAluno.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTabelaEditarAluno.getColumnModel().getColumn(2).setPreferredWidth(600);

        jTabelaEditarAluno.getColumnModel().getColumn(3).setPreferredWidth(400);
        jTabelaEditarAluno.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTabelaEditarAluno.getColumnModel().getColumn(5).setPreferredWidth(500);
        jTabelaEditarAluno.getColumnModel().getColumn(6).setPreferredWidth(800);

        preencherTabela();

    }//GEN-LAST:event_formWindowOpened

    private void jTabelaEditarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaEditarAlunoMouseClicked
        preencherCampos();
    }//GEN-LAST:event_jTabelaEditarAlunoMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarALuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarALuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarALuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarALuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarALuno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormatteCpf;
    private javax.swing.JFormattedTextField jFormatteRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaEditarAluno;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPeriodo;
    // End of variables declaration//GEN-END:variables
}
