/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view.aluno;

import br.com.biblioteca.Modeloprincipal.Aluno;
import br.com.biblioteca.controle.AlunoControle;
import br.com.biblioteca.facede.ImplFacade;
import br.com.biblioteca.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class RemoverAluno extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    private List<Aluno> listarAluno = new ArrayList();

    private AlunoControle alunoControle = new AlunoControle();

    /**
     * Creates new form RemoverAluno
     */
    public RemoverAluno() {
        initComponents();
    }

    public void preencherTabela() {
        modelo.setRowCount(0);

        try {
            List<Aluno> listarAluno = alunoControle.listarAlunos();

            for (Aluno aluno : listarAluno) {

                modelo.addRow(new Object[]{aluno.getId(), aluno.getNome(), aluno.getCpf(),
                    aluno.getRg(), aluno.getMatricula(), aluno.getPeriodo(), aluno.getCurso()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableExcluirAluno.setModel(modelo);
            

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(BuscarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcluirAluno = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Excluir Aluno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        jTableExcluirAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableExcluirAluno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 860, 226));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 93, 34));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTableExcluirAluno.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE_ELEMENTO_TABELA,"ALuno"));            
        // JOptionPane.showMessageDialog(null, "Selecione um elemento da tabela!");
        } else {
            int linha = jTableExcluirAluno.getSelectedRow();

            int idAluno = (Integer) modelo.getValueAt(linha, 0);
            
            try {
                //  }
            
                
               // int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover esse Aluno ?", "removido", JOptionPane.YES_NO_OPTION);
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_PERGUNTA_REMOCAO_TABELA,"Aluno?"));
                alunoControle.RemoverAluno(idAluno);
                preencherTabela();
                
            
                
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_REMOVIDO_SUCESSO,"Aluno"));
                
            } catch (Exception ex) {
                Logger.getLogger(RemoverAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        modelo = (DefaultTableModel) jTableExcluirAluno.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("PERIODO");
        modelo.addColumn("CURSO");

         jTableExcluirAluno.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableExcluirAluno.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExcluirAluno.getColumnModel().getColumn(0).setMinWidth(0);

        jTableExcluirAluno.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTableExcluirAluno.getColumnModel().getColumn(2).setPreferredWidth(600);
        jTableExcluirAluno.getColumnModel().getColumn(3).setPreferredWidth(500);
        jTableExcluirAluno.getColumnModel().getColumn(4).setPreferredWidth(500);
        jTableExcluirAluno.getColumnModel().getColumn(5).setPreferredWidth(700);
        jTableExcluirAluno.getColumnModel().getColumn(6).setPreferredWidth(750);

        preencherTabela();
        

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExcluirAluno;
    // End of variables declaration//GEN-END:variables
}
